// Copyright 2015 ChaiShushan <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package pkgdoc

import (
	"go/doc"

	unsafe_zh_CN "github.com/chai2010/golangdoc/local/pkgdoc/zh_CN/unsafe"
)

var OriginDocPackageTable = map[string][]*doc.Package{
	"zh_CN": []*doc.Package{
		unsafe_zh_CN.OriginDocPackage,
	},
}

var TranslateDocPackageTable = map[string][]*doc.Package{
	"zh_CN": []*doc.Package{
		unsafe_zh_CN.TranslateDocPackage,
	},
}
